site_name: "Workshop: Github Self-hosted Runner on Equinix Metal"

repo_url: https://github.com/equinix-labs/github-runner-on-equinix-metal-workshop
repo_name: equinix-labs/github-runner-on-equinix-metal-workshop
edit_uri: blob/main/docs

extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md

  - Parts:
      - 1. Setup: parts/part1.md
      - 2. Deploy an Equinix Metal machine: parts/part2.md
      - 3. Setup a Github Self-hosted runner: parts/part3.md
      - 4. Executing a Github Action on your self-hosted runner: parts/part4.md

  - Conclusion: parts/conclusion.md

theme:
  name: material

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  icon:
    logo: simple/equinixmetal
  favicon: images/favicon.svg

  features:
    - navigation.top
    - search.highlight
    - navigation.footer
    - content.code.copy
    - navigation.expand

extra:
  social:
    - icon: simple/equinixmetal
      link: https://deploy.equinix.com
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/@equinixmetal
    - icon: fontawesome/brands/github
      link: https://github.com/equinix-labs
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@EquinixDevelopers

plugins:
  - search
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
  - tables
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: true
  - pymdownx.superfences
  - pymdownx.keys
